# Generated by Django 4.1.7 on 2023-04-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
