# Generated by Django 4.1.7 on 2023-05-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_seller_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='inn_code',
            field=models.CharField(max_length=13, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='org_type',
            field=models.CharField(max_length=10, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(max_length=50, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_tags',
            field=models.TextField(verbose_name='Категории'),
        ),
    ]
