# Generated by Django 4.1.7 on 2023-04-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('is_seller', 'Can add, delete and change products')]},
        ),
    ]
