# Generated by Django 4.1.7 on 2023-04-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='seller',
        ),
    ]
