# Generated by Django 4.1.7 on 2023-04-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_orderinfo_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='basket',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
