# Generated by Django 4.1.7 on 2023-04-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_orderitem_basket_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(default='Принят продавцом', max_length=50, verbose_name='Статус'),
        ),
    ]
