# Generated by Django 4.1.7 on 2023-04-23 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orderinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 23, 18, 39, 493634, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
