# Generated by Django 4.1.7 on 2023-04-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_seller_options'),
        ('main', '0014_alter_orderinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='userauth.seller'),
            preserve_default=False,
        ),
    ]
